### PR TITLE
Issue #1995 pod of the method table create complex

### LINKED ISSUE #1995: POD of the method TableCreateComplex
The documentation of _Kernel/Output/HTML/LinkObject/Appointment.pm_ and  _Kernel/Output/HTML/LinkObject/Ticket.pm_ iTs lacking. In `TableCreateComplex()` the returned attribute `AllColumns` is not documented and the type of the returned data structure is incorrect.

### PR DESCRIPTION
**Pull request by dennis-dko**

### CODE REVIEW

File: Kernel/Output/HTML/Layout/LinkObject.pm [hunk 1]
```diff
@@ -158,15 +158,15 @@ sub LinkObjectTableCreateComplex {
         next OBJECT if !$BackendObject;
 
         # get block data
-        my @BlockData = $BackendObject->TableCreateComplex(
+        my $BlockData = $BackendObject->TableCreateComplex(
```
Comment (bschmalhofer) [inline Kernel/Output/HTML/Layout/LinkObject.pm]: I think that @BlockData is correct, as there could be multiple hash references returned.

File: Kernel/Output/HTML/LinkObject/Ticket.pm [hunk 2]
```diff
@@ -100,7 +100,7 @@ return an array with the block data
 
 Return
 
-    %BlockData = (
+    $BlockData = {
```
Comment (bschmalhofer) [inline Kernel/Output/HTML/LinkObject/Ticket.pm]: If I understand the interface correctly, this line should be:
my @BlockData = (

File: Kernel/Output/HTML/LinkObject/Ticket.pm [hunk 3]
```diff
@@ -153,10 +153,53 @@ Return
...
+                    ColumnTranslate => 'XXX',
+                },
+                ....
+            ],
         },
-    );
+    };
 
-    @BlockData = $BackendObject->TableCreateComplex(
+    $BlockData = $BackendObject->TableCreateComplex(
```
Comment (bschmalhofer) [inline Kernel/Output/HTML/LinkObject/Ticket.pm]: This example call should be placed before the example result.

**Review by bschmalhofer — APPROVED** [review]
Looks good.
cpanfile.docker was only changed to invalidate the cpanm chache used in the CI workflow.
